# Configuration for QuantaGlia System

main:
  knowledge_base: "./knowledge_base"
  repo_cache: "./repo_cache"
  target_topics:
    - "README"
    - "LICENSE"
    - "CONTRIBUTING"
    - "ethics"
    - "usage"
  max_repos: 10

# Configuration for QuantaGlia Pruner
pruning:
  # The interval in minutes for periodic pruning runs.
  interval_minutes: 1440 # 24 hours

  # Repositories older than this will be considered for pruning.
  age_threshold_days: 90

  # The default strategy for the pruner.
  # "conservative": Archives repositories. Deletion is disabled.
  # "aggressive": Allows deletion of repositories.
  default_strategy: "conservative"

  # Path to the directory where archived repositories are moved.
  archive_path: "repo_archive/"

  # Weights for the composite score calculation (mocked for Phase II)
  scoring_weights:
    usage: 0.5
    age: 0.2
    redundancy: 0.2
    ethics_risk: 0.1

  # Decision thresholds for the final score
  decision_thresholds:
    delete: 0.9  # Score >= 0.9 -> DELETE (if strategy is aggressive)
    archive: 0.7 # Score >= 0.7 -> ARCHIVE
    review: 0.5  # Score >= 0.5 -> Flag for human review

# Configuration for LLaMA.cpp integration
llamacpp:
  url: "http://localhost:8080/completion"
  enabled: true
