# Configuration for QuantaGlia System

main:
  knowledge_base: "./knowledge_base"
  repo_cache: "./repo_cache"
  target_topics:
    - "README"
    - "docs"
    - "ethics"
    - "usage"
  max_repos: 10

# Configuration for QuantaGlia Pruner
pruning:
  age_threshold_days: 30

# Configuration for LLaMA.cpp integration
llamacpp:
  url: "http://localhost:8080/completion"
  enabled: false
