# Configuration for QuantaGlia System

main:
  knowledge_base: "./knowledge_base"
  repo_cache: "./repo_cache"
  target_topics:
    - "README"
    - "docs"
    - "ethics"
    - "usage"
  max_repos: 10

# Configuration for QuantaGlia Pruner
pruning:
  # The interval in minutes for periodic pruning runs.
  interval_minutes: 1440 # 24 hours

  # Repositories older than this will be considered for pruning.
  age_threshold_days: 90

  # The default strategy for the pruner.
  # "conservative": Archives repositories. Deletion is disabled.
  default_strategy: "conservative"

  # Path to the directory where archived repositories are moved.
  archive_path: "repo_archive/"

# Configuration for LLaMA.cpp integration
llamacpp:
  url: "http://localhost:8080/completion"
  enabled: false
